name: nightly

on: [push, pull_request]

jobs:

    tests:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ['3.8', '3.10']

        services:
            postgres:
                image: postgres:12
                env:
                    POSTGRES_DB: test_aiida
                    POSTGRES_PASSWORD: ''
                    POSTGRES_HOST_AUTH_METHOD: trust
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                -   5432:5432
            rabbitmq:
                image: rabbitmq:latest
                ports:
                -   5672:5672

        steps:
        -   uses: actions/checkout@v2

        -   name: Cache Python dependencies
            uses: actions/cache@v1
            with:
                path: ~/.cache/pip
                key: pip-${{ matrix.python-version }}-tests-${{ hashFiles('**/setup.json') }}
                restore-keys:
                    pip-${{ matrix.python-version }}-tests

        -   name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
                python-version: ${{ matrix.python-version }}

        -   name: Install system dependencies
            run: sudo apt update && sudo apt install postgresql

        -   name: Install aiida-optimize (aiida-core)
            run: |
                pip install -e .
                pip freeze

        -   name: Setup environment
            run: .github/system_tests/setup.sh

        -   name: Run tests
            run: .github/system_tests/tests_daemon.sh